# Generated by Django 5.2.3 on 2025-06-24 20:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='parkingspace',
            name='parking',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='vaga',
        ),
        migrations.CreateModel(
            name='Estacionamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entrada', models.DateTimeField(auto_now_add=True)),
                ('saida', models.DateTimeField(blank=True, null=True)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.vaga')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.veiculo')),
            ],
        ),
        migrations.DeleteModel(
            name='Parking',
        ),
        migrations.DeleteModel(
            name='ParkingSpace',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
